apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-config-deployment
  labels:
    app: backend-config-deployment
spec:
  selector:
    matchLabels:
      app: backend-config-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-config-deployment
    spec:
      containers:
        - name: backend-config-service
          image: donuldaricio/backend-config-service:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: backend-config-service
  labels:
    app: backend-config-service
spec:
  selector:
    app: backend-config-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: LoadBalancer