apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-arancel-deployment
  labels:
    app: backend-arancel-deployment
spec:
  selector:
    matchLabels:
      app: backend-arancel-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-arancel-deployment
    spec:
      containers:
        - name: backend-arancel-service
          image: donuldaricio/backend-estudiante-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config-service:8090
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_ARANCELES
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_ARANCELES
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-arancel-service
  labels:
    app: backend-arancel-service
spec:
  selector:
    app: backend-arancel-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer