server:
  port: 8090
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Don-Uldaricio/TingesoEntrega2
          search-paths: config-data